name: full CI for bluesky-selfhost-env run by manual.

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  #REGISTRY: docker.io
  TZ: ${{ vars.TZ }}
  opsBranch: ${{ vars.opsBranch}}
  fork_repo_prefix: ${{ vars.fork_repo_prefix }}

  builder: ${{ vars.builder }}
  buildContainers: ${{ vars.buildContainers }}
  buildImage: ${{ vars.buildImage }}
  user: ${{ github.repository_owner }}
  gh_secret: ${{secrets.GH_TOKEN_WORKFLOW }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: adjust env
        run : |
           echo asof=ci-$(date +'%Y%m%d-%H%M%S') >> $GITHUB_ENV
           echo topDir=${GITHUB_WORKSPACE} >> $GITHUB_ENV
           echo rDir=${GITHUB_WORKSPACE}/ops/repos >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: pull from repos ${{env.asof}}
        run: |
          env | sort --ignore-case
          git clone https://github.com/itaru2622/bluesky-selfhost-env.git ops
          (cd ops; \
              git checkout origin/${opsBranch} -b ${opsBranch}; \
              make cloneAll; \
          )

      - name: git log    upstream/main from fork/main ${{env.asof}}
        run: |
          (cd ops; \
              make exec under=repos/* cmd='\
                 git log --format="%ad ;   %h ; %aL ; %s ;%d" --date=format:%Y-%m-%dT%H:%M:%S --decorate-refs=refs/tags/ --decorate=full fork/main   > /tmp/log-fork-$${r}     ; \
                 git log --format="%ad ;   %h ; %aL ; %s ;%d" --date=format:%Y-%m-%dT%H:%M:%S --decorate-refs=refs/tags/ --decorate=full origin/main > /tmp/log-upstream-$${r} ; \
                 diff -u /tmp/log-fork-$${r} /tmp/log-upstream-$${r} | grep ^+ | tail -n +2 | sed 's/^+//' | tee ${topDir}/log-commits/$${r};' ; \
          )

      - name: statistics of commit diff ${{env.asof}}
        run: |
          (cd ${topDir}/log-commits/; \
              wc -l *; \
          )

      - name: check if new tag exists in the diff of commits ${{env.asof}}
        run: |
          (cd ${topDir}/log-commits/; \
              grep \; * | sed -e 's/:/;/' | awk -F\; '{print $1" ; "$2";"$3";"$6}' | grep -v ';$' | cat
          )

      - name: patch apply ${{env.asof}}
        run: |
          (cd ops; \
              make exec under=${rDir}/* cmd='git config --local user.email "github-actions[bot]@users.noreply.github.com"; git config --local user.name  "github-actions[bot]" '; \
              make exec under=${rDir}/* cmd='git checkout -b work'; \
              make patch-dockerbuild; \
          )
          echo "########### find .rej ################"
          find ${rDir} -type f | grep -v /.git | grep .rej$ | cat
          code=`find ${rDir} -type f | grep -v /.git | grep .rej$ | cat | wc -l`
          echo $code
          # code==0 => ok otherwise failure
          exit $code

      - name: cleanup docker env to avoid no disk space ${{env.asof}}
#       if: ${{env.buildImage == 'true' }}
        run: |
           docker system df
           docker system df -v
           docker system prune -a --volumes -f
           docker system df
           docker system df -v

      - name: build docker image ${{env.asof}} ${{env.buildContainers}}
#       if: ${{env.buildImage == 'true' }}
        run: |
          (cd ops; \
              git branch | cat; \
              cat ${builder} | yq '.services | keys'; \
              make build dockerCompose='docker compose' DOMAIN= f=${builder} services="${buildContainers}" ; \
          )
      - name: images ${{env.asof}}
#       if: ${{env.buildImage == 'true' }}
        run: |
          docker images | grep itaru2622/bluesky

      - name: push docker image to remote registry ${{env.asof}}
#       if: ${{env.buildImage == 'true' }}
        run: |
          # login to docker registry
          echo ${gh_secret} | docker login ${REGISTRY} -u ${user} --password-stdin

          # pick image and assign tag for upload then push it.
          for i in `docker images | grep itaru2622/bluesky | awk -v c=':' '{print $1 c $2}' ` ; do
              echo $i;
              docker tag $i ${REGISTRY}/$i;
              docker push   ${REGISTRY}/$i;
          done
          #docker push  ${REGISTRY}/${user}/apline:latest
          docker logout ${REGISTRY}
